-- FUNON — abordagens, retornos, scripts e histórico (incremental)

ALTER TABLE IF EXISTS client_approaches RENAME TO approaches;

CREATE TABLE IF NOT EXISTS approach_result_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  suggest_follow_up BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS closure_reason_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('pause', 'close')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS message_scripts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  script_type TEXT NOT NULL CHECK (script_type IN ('call', 'whatsapp')),
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE approaches ADD COLUMN IF NOT EXISTS contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE approaches ADD COLUMN IF NOT EXISTS product_id INTEGER REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE approaches ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ;
ALTER TABLE approaches ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE approaches ADD COLUMN IF NOT EXISTS result_type_id INTEGER REFERENCES approach_result_types(id) ON DELETE SET NULL;
ALTER TABLE approaches ADD COLUMN IF NOT EXISTS external_call_id TEXT;

UPDATE approaches SET occurred_at = created_at WHERE occurred_at IS NULL;
UPDATE approaches SET channel = 'call' WHERE channel IS NULL OR channel = '';

ALTER TABLE approaches ALTER COLUMN occurred_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS follow_ups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  source_approach_id INTEGER REFERENCES approaches(id) ON DELETE SET NULL,
  kind TEXT NOT NULL DEFAULT 'return' CHECK (kind IN ('return', 'meeting')),
  assigned_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  scheduled_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'cancelled')),
  notes TEXT,
  completed_at TIMESTAMPTZ,
  completed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  completion_approach_id INTEGER REFERENCES approaches(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS temperature TEXT CHECK (temperature IN ('cold', 'warm', 'hot'));
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS engagement_status TEXT NOT NULL DEFAULT 'active'
  CHECK (engagement_status IN ('active', 'paused', 'closed'));
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS pause_reason_id INTEGER REFERENCES closure_reason_types(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS close_reason_id INTEGER REFERENCES closure_reason_types(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMPTZ;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS status_changed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS contact_verification_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  old_status TEXT,
  new_status TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS opportunity_temperature_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id INTEGER NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  old_temperature TEXT,
  new_temperature TEXT,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_approaches_client_occurred ON approaches (client_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_approaches_user_occurred ON approaches (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_follow_ups_assigned_status_sched ON follow_ups (assigned_user_id, status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_follow_ups_client ON follow_ups (client_id, status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_message_scripts_type_status ON message_scripts (script_type, status);
CREATE INDEX IF NOT EXISTS idx_contact_verification_logs_client ON contact_verification_logs (client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_opportunity_temperature_logs_client ON opportunity_temperature_logs (client_id, created_at DESC);

INSERT INTO approach_result_types (slug, name, sort_order, suggest_follow_up) VALUES
  ('nao_atendeu', 'Não atendeu', 1, false),
  ('chamou_sem_resposta', 'Chamou sem resposta', 2, false),
  ('numero_invalido', 'Número inválido', 3, false),
  ('falou_outra_pessoa', 'Falou com outra pessoa', 4, false),
  ('falou_responsavel', 'Falou com o responsável', 5, false),
  ('pediu_retorno', 'Pediu retorno', 6, true),
  ('demonstrou_interesse', 'Demonstrou interesse', 7, true),
  ('sem_interesse', 'Sem interesse', 8, false),
  ('reuniao_agendada', 'Reunião agendada', 9, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO closure_reason_types (slug, name, kind, sort_order) VALUES
  ('fora_perfil', 'Fora do perfil', 'close', 1),
  ('ja_possui_solucao', 'Já possui solução', 'close', 2),
  ('pausa_temporaria', 'Pausa temporária', 'pause', 3),
  ('sem_retorno', 'Sem retorno do cliente', 'pause', 4)
ON CONFLICT (slug) DO NOTHING;
