-- Reuniões comerciais e integração Google Agenda (incremental)

CREATE TABLE IF NOT EXISTS meetings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  opportunity_id INTEGER REFERENCES opportunities(id) ON DELETE SET NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
  bdr_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  source_approach_id INTEGER REFERENCES approaches(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  duration_minutes INTEGER NOT NULL DEFAULT 30 CHECK (duration_minutes > 0 AND duration_minutes <= 480),
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN (
    'scheduled', 'confirmed', 'held', 'no_show', 'cancelled', 'rescheduled'
  )),
  notes TEXT,
  summary TEXT,
  interest_notes TEXT,
  next_step TEXT,
  created_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  idempotency_key TEXT,
  google_event_id TEXT,
  google_calendar_id TEXT,
  meet_link TEXT,
  google_sync_status TEXT NOT NULL DEFAULT 'none' CHECK (google_sync_status IN ('none', 'pending', 'synced', 'error')),
  google_sync_error TEXT,
  google_synced_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  cancelled_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  cancel_reason TEXT,
  rescheduled_at TIMESTAMPTZ,
  rescheduled_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reschedule_reason TEXT,
  previous_starts_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_meetings_idempotency ON meetings (idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_meetings_starts_at ON meetings (starts_at);
CREATE INDEX IF NOT EXISTS idx_meetings_client ON meetings (client_id, starts_at DESC);
CREATE INDEX IF NOT EXISTS idx_meetings_bdr ON meetings (bdr_user_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_meetings_status ON meetings (status, starts_at);

CREATE TABLE IF NOT EXISTS meeting_internal_participants (
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (meeting_id, user_id)
);

CREATE TABLE IF NOT EXISTS meeting_external_participants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  display_name TEXT,
  contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS meeting_status_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS google_calendar_connection (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  account_email TEXT,
  calendar_id TEXT NOT NULL DEFAULT 'primary',
  refresh_token_encrypted TEXT,
  access_token TEXT,
  access_token_expires_at TIMESTAMPTZ,
  connected_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  connected_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS google_oauth_states (
  state TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL
);
