-- Perfil admin + variáveis de sistema (APIs Google Agenda / Places)

ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS user_roles_role_check;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_role_check
  CHECK (role IN ('bdr', 'product_owner', 'manager', 'admin'));

CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general',
  value TEXT,
  is_secret BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO system_settings (key, label, category, value, is_secret) VALUES
  ('google_calendar_scheduling_email', 'E-mail da conta que agenda reuniões (Meet/Calendar)', 'google_calendar', NULL, false),
  ('google_oauth_client_id', 'Google OAuth Client ID (Agenda)', 'google_calendar', NULL, false),
  ('google_oauth_client_secret', 'Google OAuth Client Secret (Agenda)', 'google_calendar', NULL, true),
  ('google_places_api_key', 'Google Places API Key (busca de leads)', 'google_places', NULL, true),
  ('google_places_default_radius_km', 'Raio padrão da busca Places (km)', 'google_places', '25', false),
  ('lead_discovery_provider', 'Motor de novos leads (ex.: google_places)', 'lead_discovery', 'google_places', false)
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS lead_discovery_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  uf TEXT,
  cities TEXT,
  segment TEXT,
  quantity_requested INTEGER NOT NULL DEFAULT 10,
  quantity_inserted INTEGER NOT NULL DEFAULT 0,
  quantity_skipped_existing INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'running', 'completed', 'failed', 'stub')),
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);
