-- Empresas (grupo Inlift) e vínculo obrigatório em produtos

CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  legal_name TEXT,
  cnpj TEXT,
  responsible_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO companies (name, legal_name, status)
SELECT 'Inlift', 'Inlift Group', 'active'
WHERE NOT EXISTS (SELECT 1 FROM companies LIMIT 1);

ALTER TABLE products ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);

UPDATE products SET company_id = (SELECT id FROM companies ORDER BY id LIMIT 1)
WHERE company_id IS NULL;

ALTER TABLE products ALTER COLUMN company_id SET NOT NULL;
