-- Integração API4COM: ramal por BDR e registro de chamadas

ALTER TABLE users ADD COLUMN IF NOT EXISTS api4com_extension TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_api4com_extension_active
  ON users (api4com_extension)
  WHERE api4com_extension IS NOT NULL
    AND trim(api4com_extension) <> ''
    AND status = 'active';

INSERT INTO system_settings (key, label, category, value, is_secret) VALUES
  ('api4com_api_token', 'Token API API4COM', 'api4com', NULL, true),
  ('api4com_gateway', 'Gateway / código da integração (metadata)', 'api4com', 'inlift-crm', false),
  ('api4com_webhook_secret', 'Segredo opcional para validar webhooks recebidos', 'api4com', NULL, true),
  ('api4com_base_url', 'URL base da API', 'api4com', 'https://api.api4com.com', false)
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS api4com_calls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api4com_call_id TEXT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL,
  contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  phone_dialed TEXT NOT NULL,
  extension TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'initiating'
    CHECK (status IN ('initiating', 'ringing', 'in_progress', 'completed', 'failed', 'cancelled')),
  started_at TIMESTAMPTZ,
  answered_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  duration_seconds INTEGER,
  hangup_cause_code TEXT,
  hangup_cause_label TEXT,
  record_url TEXT,
  direction TEXT,
  metadata_json TEXT,
  webhook_event_id TEXT,
  approach_id INTEGER REFERENCES approaches(id) ON DELETE SET NULL,
  result_pending BOOLEAN NOT NULL DEFAULT false,
  result_deferred_at TIMESTAMPTZ,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_api4com_calls_api_id ON api4com_calls (api4com_call_id)
  WHERE api4com_call_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_api4com_calls_webhook_event ON api4com_calls (webhook_event_id)
  WHERE webhook_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_api4com_calls_user_pending ON api4com_calls (user_id, result_pending, ended_at DESC);
