-- Geração de leads (ANP + enriquecimento) — execuções em segundo plano

CREATE TABLE IF NOT EXISTS lead_generation_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'paused', 'completed', 'failed', 'cancelled')),
  phase TEXT NOT NULL DEFAULT 'anp_load'
    CHECK (phase IN ('anp_load', 'processing', 'finalizing', 'done')),
  uf CHAR(2) NOT NULL,
  filters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  bdr_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  max_stations INTEGER NOT NULL DEFAULT 50,
  max_google_calls INTEGER NOT NULL DEFAULT 50,
  google_calls_used INTEGER NOT NULL DEFAULT 0,
  simulation BOOLEAN NOT NULL DEFAULT false,
  counts_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  progress_pct NUMERIC(5, 2) NOT NULL DEFAULT 0,
  error_message TEXT,
  cancel_requested BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_generation_runs_status ON lead_generation_runs (status, updated_at DESC);

CREATE TABLE IF NOT EXISTS lead_generation_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES lead_generation_runs(id) ON DELETE CASCADE,
  cnpj TEXT,
  anp_raw JSONB,
  station_json JSONB,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN (
      'pending', 'processing', 'existing', 'created', 'ambiguous', 'no_google_match', 'error', 'skipped_invalid_cnpj'
    )),
  client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL,
  google_place_id TEXT,
  enrichment_json JSONB,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_generation_items_run_cnpj
  ON lead_generation_items (run_id, cnpj)
  WHERE cnpj IS NOT NULL AND trim(cnpj) <> '';

CREATE INDEX IF NOT EXISTS idx_lead_generation_items_run_status
  ON lead_generation_items (run_id, status);

CREATE TABLE IF NOT EXISTS lead_generation_google_cache (
  cnpj TEXT PRIMARY KEY,
  place_id TEXT,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lead_generation_daily_usage (
  usage_day DATE PRIMARY KEY,
  google_calls INTEGER NOT NULL DEFAULT 0
);

INSERT INTO system_settings (key, label, category, value, is_secret) VALUES
  ('google_places_daily_limit', 'Limite diário de chamadas Google Places', 'google_places', '200', false),
  ('google_places_per_run_limit', 'Limite padrão Google por execução', 'google_places', '50', false),
  ('lead_generation_simulation_default', 'Modo simulação (sem APIs pagas) — 1=sim', 'lead_discovery', '1', false)
ON CONFLICT (key) DO NOTHING;
