-- Fluxos configuráveis de geração de leads

CREATE TABLE IF NOT EXISTS lead_generation_flows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT true,
  initial_source TEXT NOT NULL DEFAULT 'anp_retail'
    CHECK (initial_source IN ('anp_retail', 'anp_distributor', 'google_places_city')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lead_generation_flow_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flow_id BIGINT NOT NULL REFERENCES lead_generation_flows(id) ON DELETE CASCADE,
  step_key TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT true,
  on_fail TEXT NOT NULL DEFAULT 'continue'
    CHECK (on_fail IN ('continue', 'stop')),
  max_api_calls INTEGER,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (flow_id, step_key)
);

CREATE INDEX IF NOT EXISTS idx_lead_gen_flow_steps_flow ON lead_generation_flow_steps (flow_id, sort_order);

ALTER TABLE lead_generation_segments
  ADD COLUMN IF NOT EXISTS default_flow_id BIGINT REFERENCES lead_generation_flows(id) ON DELETE SET NULL;

ALTER TABLE lead_generation_segments
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE lead_generation_runs
  ADD COLUMN IF NOT EXISTS flow_id BIGINT REFERENCES lead_generation_flows(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS flow_snapshot_json JSONB;

-- Fluxos iniciais (etapas = módulos fixos do código)
INSERT INTO lead_generation_flows (slug, name, description, active, initial_source) VALUES
  (
    'fluxo_posto',
    'Fluxo Posto',
    'Cadastro ANP revendedores → Google Places → CNPJ (Receita) → site → Instagram.',
    true,
    'anp_retail'
  ),
  (
    'fluxo_distribuidora',
    'Fluxo Distribuidora de Combustíveis',
    'Base pública de distribuidoras ANP (parser dedicado) → enriquecimento Google e CNPJ.',
    true,
    'anp_distributor'
  ),
  (
    'fluxo_tradicional',
    'Fluxo Tradicional',
    'Busca por segmento/cidade no Google Places; CNPJ só com correspondência confiável.',
    true,
    'google_places_city'
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO lead_generation_flow_steps (flow_id, step_key, sort_order, enabled, on_fail, max_api_calls)
SELECT f.id, s.step_key, s.sort_order, true, s.on_fail, s.max_api_calls
FROM lead_generation_flows f
CROSS JOIN (
  VALUES
    ('anp_retail_list', 10, 'continue', NULL::integer),
    ('anp_distributor_list', 10, 'continue', NULL::integer),
    ('google_places_city_discover', 10, 'continue', 20),
    ('validate_cnpj', 20, 'continue', NULL),
    ('google_place_search', 30, 'stop', 2),
    ('google_place_details', 40, 'continue', 1),
    ('receita_cnpj', 50, 'continue', 1),
    ('website_enrich', 60, 'continue', NULL),
    ('instagram_enrich', 70, 'continue', NULL),
    ('create_crm_client', 90, 'stop', NULL)
) AS s(step_key, sort_order, on_fail, max_api_calls)
WHERE f.slug = 'fluxo_posto' AND s.step_key IN (
  'anp_retail_list', 'validate_cnpj', 'google_place_search', 'google_place_details',
  'receita_cnpj', 'website_enrich', 'instagram_enrich', 'create_crm_client'
)
ON CONFLICT (flow_id, step_key) DO NOTHING;

INSERT INTO lead_generation_flow_steps (flow_id, step_key, sort_order, enabled, on_fail, max_api_calls)
SELECT f.id, s.step_key, s.sort_order, true, s.on_fail, s.max_api_calls
FROM lead_generation_flows f
CROSS JOIN (
  VALUES
    ('anp_distributor_list', 10, 'continue', NULL::integer),
    ('validate_cnpj', 20, 'continue', NULL),
    ('google_place_search', 30, 'stop', 2),
    ('google_place_details', 40, 'continue', 1),
    ('receita_cnpj', 50, 'continue', 1),
    ('website_enrich', 60, 'continue', NULL),
    ('instagram_enrich', 70, 'continue', NULL),
    ('create_crm_client', 90, 'stop', NULL)
) AS s(step_key, sort_order, on_fail, max_api_calls)
WHERE f.slug = 'fluxo_distribuidora'
ON CONFLICT (flow_id, step_key) DO NOTHING;

INSERT INTO lead_generation_flow_steps (flow_id, step_key, sort_order, enabled, on_fail, max_api_calls)
SELECT f.id, s.step_key, s.sort_order, true, s.on_fail, s.max_api_calls
FROM lead_generation_flows f
CROSS JOIN (
  VALUES
    ('google_places_city_discover', 10, 'continue', 25),
    ('google_place_details', 30, 'continue', 1),
    ('validate_cnpj', 35, 'continue', NULL),
    ('receita_cnpj', 50, 'continue', 1),
    ('website_enrich', 60, 'continue', NULL),
    ('instagram_enrich', 70, 'continue', NULL),
    ('create_crm_client', 90, 'stop', NULL)
) AS s(step_key, sort_order, on_fail, max_api_calls)
WHERE f.slug = 'fluxo_tradicional'
ON CONFLICT (flow_id, step_key) DO NOTHING;

UPDATE lead_generation_segments s SET default_flow_id = f.id
FROM lead_generation_flows f
WHERE s.slug IN ('all', 'branded', 'white_flag') AND f.slug = 'fluxo_posto';

UPDATE lead_generation_segments s SET default_flow_id = f.id
FROM lead_generation_flows f
WHERE s.slug = 'distributor' AND f.slug = 'fluxo_distribuidora';

UPDATE lead_generation_segments s SET default_flow_id = f.id
FROM lead_generation_flows f
WHERE s.slug = 'trr' AND f.slug = 'fluxo_tradicional';
