-- Repara bancos onde 026 foi marcada aplicada sem lead_generation_ibge_uf_cache (ou só trecho final rodado no SQL Editor).

CREATE TABLE IF NOT EXISTS lead_generation_ibge_uf_cache (
  uf CHAR(2) PRIMARY KEY,
  municipalities_json JSONB NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source TEXT NOT NULL DEFAULT 'ibge'
    CHECK (source IN ('ibge', 'cache', 'fallback'))
);

CREATE TABLE IF NOT EXISTS lead_generation_commercial_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uf CHAR(2) NOT NULL,
  name TEXT NOT NULL,
  legacy_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (uf, name)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_gen_zones_legacy
  ON lead_generation_commercial_zones (legacy_key)
  WHERE legacy_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS lead_generation_commercial_zone_municipalities (
  zone_id BIGINT NOT NULL REFERENCES lead_generation_commercial_zones(id) ON DELETE CASCADE,
  ibge_code INTEGER NOT NULL,
  PRIMARY KEY (zone_id, ibge_code)
);

CREATE TABLE IF NOT EXISTS lead_generation_municipalities (
  ibge_code INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  uf CHAR(2) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_gen_municipalities_uf ON lead_generation_municipalities (uf);

CREATE TABLE IF NOT EXISTS lead_generation_run_municipalities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES lead_generation_runs(id) ON DELETE CASCADE,
  ibge_code INTEGER NOT NULL REFERENCES lead_generation_municipalities(ibge_code),
  commercial_zone_id BIGINT REFERENCES lead_generation_commercial_zones(id) ON DELETE SET NULL,
  UNIQUE (run_id, ibge_code)
);

CREATE INDEX IF NOT EXISTS idx_lead_gen_run_muni_ibge ON lead_generation_run_municipalities (ibge_code);

ALTER TABLE lead_generation_runs DROP CONSTRAINT IF EXISTS lead_generation_runs_status_check;
ALTER TABLE lead_generation_runs ADD CONSTRAINT lead_generation_runs_status_check
  CHECK (status IN ('queued', 'running', 'paused', 'completed', 'partial', 'failed', 'cancelled'));
