-- Perfis de acesso ao menu (independente de user_roles operacionais)

CREATE TABLE IF NOT EXISTS access_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  access_rank INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS access_profile_menu_grants (
  profile_id BIGINT NOT NULL REFERENCES access_profiles(id) ON DELETE CASCADE,
  menu_key TEXT NOT NULL,
  PRIMARY KEY (profile_id, menu_key)
);

CREATE TABLE IF NOT EXISTS user_access_profiles (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  profile_id BIGINT NOT NULL REFERENCES access_profiles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, profile_id)
);

CREATE INDEX IF NOT EXISTS idx_user_access_profiles_user ON user_access_profiles (user_id);

INSERT INTO access_profiles (slug, name, description, access_rank, active) VALUES
  (
    'operacional',
    'Operacional',
    'Prospecção, clientes, funil e cadastros do dia a dia.',
    10,
    true
  ),
  (
    'gestao',
    'Gestão',
    'Operacional + organização de leads e negócios convertidos.',
    30,
    true
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO access_profile_menu_grants (profile_id, menu_key)
SELECT p.id, k.menu_key
FROM access_profiles p
CROSS JOIN (
  VALUES
    ('dashboard'),
    ('prospeccao'),
    ('funil'),
    ('agendamentos'),
    ('organizacao_leads'),
    ('clientes'),
    ('abordagens'),
    ('resultado_comercial'),
    ('negocios_convertidos'),
    ('empresas'),
    ('produtos')
) AS k(menu_key)
WHERE p.slug = 'operacional'
ON CONFLICT DO NOTHING;

INSERT INTO access_profile_menu_grants (profile_id, menu_key)
SELECT p.id, k.menu_key
FROM access_profiles p
CROSS JOIN (
  VALUES
    ('dashboard'),
    ('prospeccao'),
    ('funil'),
    ('agendamentos'),
    ('organizacao_leads'),
    ('clientes'),
    ('abordagens'),
    ('resultado_comercial'),
    ('negocios_convertidos'),
    ('empresas'),
    ('produtos')
) AS k(menu_key)
WHERE p.slug = 'gestao'
ON CONFLICT DO NOTHING;
