-- Rodar no Supabase SQL Editor ANTES de 005_fix_004_backfill.sql
-- se aparecer "column opportunities.title does not exist".
-- (Registrar em schema_migrations não aplica o DDL — só marca como feito.)

-- Etapas comerciais
CREATE TABLE IF NOT EXISTS pipeline_stages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '#525252',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  kind TEXT NOT NULL DEFAULT 'in_progress' CHECK (kind IN ('in_progress', 'won', 'lost')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO pipeline_stages (name, sort_order, color, status, kind)
SELECT v.name, v.sort_order, v.color, 'active', v.kind
FROM (VALUES
  ('Agendado', 10, '#6366f1', 'in_progress'),
  ('Interessado', 20, '#0ea5e9', 'in_progress'),
  ('Proposta enviada', 30, '#f59e0b', 'in_progress'),
  ('Formalizando', 40, '#a855f7', 'in_progress'),
  ('Convertido', 50, '#22c55e', 'won'),
  ('Perdido', 60, '#ef4444', 'lost')
) AS v(name, sort_order, color, kind)
WHERE NOT EXISTS (SELECT 1 FROM pipeline_stages LIMIT 1);

-- Motivos de perda (cadastro editável)
CREATE TABLE IF NOT EXISTS opportunity_loss_reasons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO opportunity_loss_reasons (name, status)
SELECT v.name, 'active'
FROM (VALUES
  ('Preço'),
  ('Concorrente'),
  ('Sem budget'),
  ('Timing / adiou'),
  ('Sem resposta'),
  ('Outro')
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM opportunity_loss_reasons LIMIT 1);

-- Expandir oportunidades (negociações)
ALTER TABLE opportunities DROP CONSTRAINT IF EXISTS opportunities_client_id_product_id_key;

ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS origin_bdr_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS closer_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS pipeline_stage_id INTEGER REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS estimated_value NUMERIC(14, 2);
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS estimated_value_tbd BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS expected_close_date DATE;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS outcome TEXT NOT NULL DEFAULT 'open'
  CHECK (outcome IN ('open', 'won', 'lost'));
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS lost_reason_id INTEGER REFERENCES opportunity_loss_reasons(id) ON DELETE SET NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS lost_notes TEXT;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;

-- Histórico de etapas
CREATE TABLE IF NOT EXISTS opportunity_stage_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id INTEGER NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  from_stage_id INTEGER REFERENCES pipeline_stages(id) ON DELETE SET NULL,
  to_stage_id INTEGER NOT NULL REFERENCES pipeline_stages(id) ON DELETE RESTRICT,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_opportunity_stage_logs_opp ON opportunity_stage_logs (opportunity_id, created_at DESC);

-- Propostas
CREATE TABLE IF NOT EXISTS opportunity_proposals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id INTEGER NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  original_filename TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  mime_type TEXT,
  file_size_bytes INTEGER NOT NULL,
  proposed_value NUMERIC(14, 2),
  valid_until DATE,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'sent', 'accepted', 'rejected', 'superseded')),
  sent_at TIMESTAMPTZ,
  sent_channel TEXT,
  uploaded_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (opportunity_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_opportunity_proposals_opp ON opportunity_proposals (opportunity_id, version_number DESC);

-- Fotografia de conversão + correções
CREATE TABLE IF NOT EXISTS opportunity_conversion_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id INTEGER NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  closer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  closed_at TIMESTAMPTZ NOT NULL,
  deal_value NUMERIC(14, 2),
  deal_value_tbd BOOLEAN NOT NULL DEFAULT false,
  recorded_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_current BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS opportunity_conversion_amendments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id INTEGER NOT NULL REFERENCES opportunity_conversion_snapshots(id) ON DELETE CASCADE,
  opportunity_id INTEGER NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
  previous_closer_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  previous_closed_at TIMESTAMPTZ,
  previous_deal_value NUMERIC(14, 2),
  previous_deal_value_tbd BOOLEAN,
  new_closer_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  new_closed_at TIMESTAMPTZ,
  new_deal_value NUMERIC(14, 2),
  new_deal_value_tbd BOOLEAN,
  reason TEXT NOT NULL,
  amended_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
